[Email][Templates] Ecoquartiers version
betagouv/recoco-portails pull request #2
Opened 2022-09-13 15:49 UTC by qdanneville

Email surcharge for Ecoquartiers

2022-09-13 15:51 UTC, glibersat requested changes
Il ne manquerait pas le template text côté magicauth
ainsi que le nouveau fichier email_subject.txt pour magicauth ?

2022-09-13 15:56 UTC, glibersat commented
> Le `email.txt` n'est pas utilisé, le email_sent.html override celui-ci justement, c'est pour ça qu'il est pas poussé ici
Je ne pense pas. La version .txt est toujours utilisée et envoyée pour les clients non HTML. Je pense qu'il faut tout surcharger

> Et par rapport au email_subjet.txt, la variable dans `common.py` s'occupe de ça justement.
Non, pour supporter le multisite, j'ai du la modifier et introduire un nouveau template.
Il est là : https://github.com/glibersat/django-magicauth/blob/master/magicauth/templates/magicauth/email_subject.txt

2022-09-13 17:14 UTC, glibersat commented
Il manque ceux d'urbanvitaliz ! :)

2022-09-15 08:38 UTC, glibersat commented
@qdanneville il manque le email text pour UV

2022-09-15 08:41 UTC, qdanneville commented
> @qdanneville il manque le email text pour UV

ça marche, vu qu'il était sur l'autre repo, je me disais que c'était bon, my bad

2022-09-19 10:42 UTC, merged